== Что это

Прошивка, схема и документация на мой вариант устройства LCD2USB. Оригинальное устройство https://github.com/harbaum/LCD2USB[тут]

== Подготовка к компиляции в Windows
Нужно установить http://winavr.sourceforge.net/download.html[WinAVR].

Для работы потребуется git bash (ну может и с другими реализациями bash тоже заработает).

Сборочные цели:

    make clean # Очистить рабочую папку
    make all # собрать проект
    make flash # залить прошивку
    make fuse # записать настроечные флаги микроконтроллера

== Компиляция и прошивка bootloader
Используя usbasp, прошить bootloader:

    cd bootloader/firmware
    make clean flash
    make fuse

[[flash-firmware]]
== Компиляция основной прошивки
  cd firmware
  make clean all

== Использование bootloader
. Подключить устройство (без программатора) с нажатой кнопкой. Должен загореться светодиод - индикатор режима прошивки. А в диспетчере устройств должно появиться устройство *HID\VID_16C0&PID_05DF&REV_0100*. Кнопку можно отпустить
. Собрать основную прошивку (см. <<flash-firmware>>)
. Запустить процесс прошивки:
    bootloader/commandline/flash.bat

или

    bootloader/commandline/bootloadHID.exe firmware/firmware-avrusb.hex

. Отключить устройство и подключить снова.
. Должна запуститься новая прошивка.

== Использование в Windows
1. Прошитое устройство подключить и убедиться, что в диспетчере устройств появилось нечто с id *USB\VID_0403&PID_C630&REV_010:*.
1. Скачать и распаковать https://sourceforge.net/projects/libusb-win32/[libusb-win32].
1. Запустить *bin/inf-wizard.exe*.
1. Выбрать из списка устройство с Vendor ID = *0x0403* и Product id *0xC630* и описанием *LCD2USB Interface*.
1. Указать целевую папку для создания комплекта драйверов.
1. Перейти в *Параметры* - *Обновление и безопасность* - *Восстановление* - *особые варианты* - *перезагрузить сейчас*.
1. После перезагрузки: *Поиск и устранение неисправностей*(или *Диагностика*) - *Доп. параметры загрузки* - *Перезагрузить*.
1. После перезагрузки выбрать 7-й пункт (отключение проверки подписи драйверов) нажатием *7* или *F7* или *Fn+F7* на некоторых ноутбуках.
1. После загрузки находим в диспетчере устройств LCD2USB и устанавливаем ранее созданный драйвер.
1. Качаем https://sourceforge.net/projects/lcdsmartie/[LcdSmartie] и куда-нибудь распаковываем.
1. Качаем https://github.com/harbaum/LCD2USB/blob/master/contrib/LCD2USB.dll[файл дисплея], который нужен, чтобы научить LCDSmartie общаться с устройством LCD2USB.
1. Кладём *lcd2usb.dll* в папку *lcdsmartie/displays*.
1. Запускаем lcdsmartie. Всё должно работать.
